### ISSUE TITLE
Rare Exception: Server url is not initialised

### ISSUE THREAD

**Issue by hooram** [savvasdalkitsis/uhuruphotos-android#33]
```
2022-05-14 10:21:50,980 WARN  [DynamicDomainInterceptor:36 intercept]: java.io.IOException: Server url is not initialised
	at com.savvasdalkitsis.uhuruphotos.auth.network.DynamicDomainInterceptor.intercept(DynamicDomainInterceptor.kt:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.savvasdalkitsis.uhuruphotos.network.interceptors.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:26)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source:79)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source:2)
	at java.lang.Thread.run(Unknown Source:4)

2022-05-14 11:34:20,516 WARN  [DynamicDomainInterceptor:36 intercept]: java.io.IOException: Server url is not initialised
	at com.savvasdalkitsis.uhuruphotos.auth.network.DynamicDomainInterceptor.intercept(DynamicDomainInterceptor.kt:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.savvasdalkitsis.uhuruphotos.network.interceptors.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:26)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source:79)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source:2)
	at java.lang.Thread.run(Unknown Source:4)

2022-05-14 15:20:22,029 ERROR [ActivityThread:621 performLaunchActivity]: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.savvasdalkitsis.uhuruphotos/com.savvasdalkitsis.uhuruphotos.app.AppActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.ViewGroup.getChildAt(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:621)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:47)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:63)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:43)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:244)
	at android.app.ActivityThread.main(Unknown Source:101)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.ViewGroup.getChildAt(int)' on a null object reference
	at androidx.activity.compose.ComponentActivityKt.setContent(ComponentActivity.kt:55)
	at androidx.activity.compose.ComponentActivityKt.setContent$default(ComponentActivity.kt:49)
	at com.savvasdalkitsis.uhuruphotos.app.AppActivity.onCreate(AppActivity.kt:44)
	at android.app.Activity.performCreate(Unknown Source:19)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:376)
	... 11 more
```

**Comment by savvasdalkitsis** [comment]
The underlying error here is an NPE when initializing the main view. I've seen this a couple of times on the cvrash reporting tool. Looks like a weird Jetpack compose bug that I cannot reproduce unfortunately and can't seem to find references to. My hope is that newer versions of the compose library will resolve this.

**Comment by savvasdalkitsis** [comment]
Raised here: https://issuetracker.google.com/issues/233251826
