### ISSUE TITLE
Bug: Spashscreen stuck if you set up both options

### ISSUE THREAD

**Issue by Jamminroot** [savvasdalkitsis/uhuruphotos-android#422]
Hey!

Great app so far, but I've been struggling a bit with a bug - when I checked local gallery, and then set up librephotos integration on the second button, "save" button disappeared, and even restarting the app did not fix that.

Worked this around by logging out, saving with just one option, and then logging back in with app interface.

Second question is regarding folders other than "Camera" - will they be scanned and synced with librephotos by any chance? It'd be good to upload those, too

Additionally, app crashed on "Syncing local media..." - I did not file an issue for that, as Im not sure that wasn't flaky behaviour. Might collect logcat for you, would you need that.

Apologies for not making those into separate issues, as I did not feel like spamming with them and forcing you to go around answering the same person in different pages:)

Oh, and big ups for proper foldables support <3

**Comment by Jamminroot** [comment]
Exception found in com.savvasdalkitsis.uhuruphotos (v0.0.138)

```
2023-08-19 16:06:50,202 WARN  [CredentialProviderBaseController$Companion:98 getCredentialExceptionTypeToException$credentials_play_services_auth_release]: androidx.credentials.exceptions.NoCredentialException: During begin sign in, failure response from one tap: 16: Cannot find a matching credential.
	at androidx.credentials.playservices.controllers.CredentialProviderBaseController$Companion.getCredentialExceptionTypeToException$credentials_play_services_auth_release(CredentialProviderBaseController.kt:98)
	at androidx.credentials.playservices.controllers.BeginSignIn.CredentialProviderBeginSignInController$resultReceiver$1$onReceiveResult$1.invoke(CredentialProviderBeginSignInController.kt:93)
	at androidx.credentials.playservices.controllers.BeginSignIn.CredentialProviderBeginSignInController$resultReceiver$1$onReceiveResult$1.invoke(CredentialProviderBeginSignInController.kt:93)
	at androidx.credentials.playservices.controllers.CredentialProviderController.maybeReportErrorFromResultReceiver(CredentialProviderController.kt:155)
	at androidx.credentials.playservices.controllers.BeginSignIn.CredentialProviderBeginSignInController.access$maybeReportErrorFromResultReceiver(CredentialProviderBeginSignInController.kt:55)
	at androidx.credentials.playservices.controllers.BeginSignIn.CredentialProviderBeginSignInController$resultReceiver$1.onReceiveResult(CredentialProviderBeginSignInController.kt:91)
	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

2023-08-19 16:07:41,313 WARN  [:null null]: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@a4c46e7

2023-08-19 16:07:44,558 WARN  [CredentialProviderController$Companion:110 maybeReportErrorResultCodeGet]: androidx.credentials.exceptions.GetCredentialCancellationException: activity is cancelled by the user.
	at androidx.credentials.playservices.controllers.CredentialProviderController$Companion.maybeReportErrorResultCodeGet(CredentialProviderController.kt:110)
	at androidx.credentials.playservices.controllers.CredentialProviderController.maybeReportErrorResultCodeGet(Unknown Source:2)
	at androidx.credentials.playservices.controllers.BeginSignIn.CredentialProviderBeginSignInController.handleResponse$credentials_play_services_auth_release(CredentialProviderBeginSignInController.kt:135)
	at androidx.credentials.playservices.controllers.BeginSignIn.CredentialProviderBeginSignInController$resultReceiver$1.onReceiveResult(CredentialProviderBeginSignInController.kt:98)
	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

2023-08-19 16:09:54,942 WARN  [<MediaStore> :null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:10:07,372 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:10:07,897 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:10:33,896 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:10:34,404 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:10:34,405 TRACE [<OkHttp> LogKt:26 log]: <-- HTTP FAILED: java.io.IOException: Canceled
2023-08-19 16:12:36,836 WARN  [:null null]: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=JobImpl{Cancelling}@d38d884

2023-08-19 16:13:01,746 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,749 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,786 WARN  [<MediaStore> :null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,794 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,815 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,818 TRACE [<Seam> LogKt:26 log]: Received mutation AvatarUpdate(avatarState=AvatarState(avatarUrl=https://home.youdev.ru/media/avatars/Dmitriiavatar.png, initials=DC, userFullName=Dmitrii Chichuk, serverUrl=https://home.youdev.ru, syncState=IN_PROGRESS)) due to action Right(value=Load)
2023-08-19 16:13:01,819 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,828 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,829 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,829 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,829 TRACE [<Seam> LogKt:26 log]: Received mutation ShowLocalMediaSyncRunning(running=true) due to action Left(value=LoadFeed)
2023-08-19 16:13:01,860 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,861 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,866 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:01,870 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:03,604 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:04,424 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:04,425 TRACE [<OkHttp> LogKt:26 log]: --> GET https://home.youdev.ru/api/user/1/
2023-08-19 16:13:04,927 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:23,799 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:23,800 TRACE [<OkHttp> LogKt:26 log]: <-- HTTP FAILED: java.io.IOException: Canceled
2023-08-19 16:13:29,740 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:53,121 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:13:59,866 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:14:13,871 WARN  [:null null]: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled

2023-08-19 16:14:13,879 TRACE [<OkHttp> LogKt:26 log]: <-- HTTP FAILED: java.io.IOException: Canceled

```

**Comment by savvasdalkitsis** [comment]
Hm that's interesting. I have not seen the issue with the onboarding screen and cannot seem to replicate it. Will do some more digging in the logic and see if i missed something that would cause this sporadically.

On your second question. Non default folders are only visible in the Library at the moment. I have plans to allow the user to select a different or more than one folders to sync in the future. Not sure when I will implement that though yet.

The crash is worrying but the logs are not helpful as they are all handled exceptions that shouldn't crash the app. if you see if again, try sending logs again soon after in case the crash is caught. I will also check in the AppCenter logs to see if the crash made it there.

Lastly, I didn't do any specific foldables work (i did make sure the app worked on tablets though so it benefited from that.) I have a separate issue to do proper foldable support (middle screen splits etc). You can track it here if you want: https://github.com/savvasdalkitsis/uhuruphotos-android/issues/5

**Comment by Jamminroot** [comment]
Interesting. That would mean that android (or some ui library you are using) handles layout automagically - as the main menu moved to the left side of screen for me.

**Comment by savvasdalkitsis** [comment]
Yes that's the 'tablet' UI. Android's UI is reactive so the inside screen of a foldable acts like a small tablet so it scales automatically :)

**Comment by Jamminroot** [comment]
I think that's fixed now - didn't get the problem after an update. Thanks!
