### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by savvasdalkitsis** [savvasdalkitsis/uhuruphotos-android#51]
```
ERROR [JsonUtf8Reader:674 nextString]: com.squareup.moshi.JsonDataException: Expected a string but was BEGIN_OBJECT at path $.people[0]
	at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:674)
	at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:250)
	at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:247)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:81)
	at com.squareup.moshi.CollectionJsonAdapter$2.fromJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at com.savvasdalkitsis.uhuruphotos.photos.service.model.PhotoResultJsonAdapter.fromJson(PhotoResultJsonAdapter.kt:93)
	at com.savvasdalkitsis.uhuruphotos.photos.service.model.PhotoResultJsonAdapter.fromJson(PhotoResultJsonAdapter.kt:24)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:46)
	at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
```

**Comment by savvasdalkitsis** [comment]
The people object representation has changed at some point causing a breaking change which the app could not handle.  Need to update the following endpoints:

/api/photosedit/favorite/
/api/albums/auto/{id}/
/api/photos/{id}

**Comment by savvasdalkitsis** [comment]
Relates to https://github.com/LibrePhotos/librephotos/issues/513
