### ISSUE TITLE
Synching does not resume

### ISSUE THREAD

**Issue by HMKnapp** [savvasdalkitsis/uhuruphotos-android#721]
App looks great, but it is unreliable for backups right now. You have to check manually if it really synched all photos and you can never be sure.

When it stops you cannot get it to start again. It should **always** and **automatically** resume, no matter the reason for stopping.

I tried:
- unticking then ticking the Cloud Sync checkbox
- Full feed sync
- Scan local media

to no effect.

The only solution right now it uninstall the app or clear storage, then install again.

This is the best photo sync app for Android. Please make backups reliable, this is much more important than any new feature.

**Comment by HMKnapp** [comment]
I believe this bug has to do with Scan local media. After a fresh install the scanning takes a while and during that time synching works as expected.

Then you leave your phone to sync and later pick it up and synching/uploading looks like it has completed but in fact it stopped after some time and it did not synch all photos, only a few weeks or months of photos.

It is then that the bug occurs. It cannot resume synching anymore. Scan local media now takes only half a second, not like when it is newly installed. It looks like the scan job aborts and no uploads are being made.

As mentioned, workaround is to reinstall the app. On first launch it scans local media properly again and resumes synching/uploads.

Hope this helps you identify the issue.

**Comment by HMKnapp** [comment]
Seems to be an OOM problem why it stops. (Phone has 6GB of RAM)

An excerpt from the logs:
```
[V] 2024-05-18 10:58:07.860 [Log.kt:27]: Found item (-1739773001, Camera)
[V] 2024-05-18 10:58:07.861 [Log.kt:27]: --> POST http://192.168.0.54:3000/api/upload/ (1000590-byte body)
[V] 2024-05-18 10:58:07.913 [Log.kt:27]: Found item (-1313584517, Screenshots)
[V] 2024-05-18 10:58:07.914 [Log.kt:27]: Found item (-1739773001, Camera)
[V] 2024-05-18 10:58:07.918 [Log.kt:27]: --> POST http://192.168.0.54:3000/api/upload/ (1000590-byte body)
[V] 2024-05-18 10:58:07.915 [Log.kt:27]: Found item (-1739773001, Camera)
[V] 2024-05-18 10:58:07.917 [Log.kt:27]: Found item (-1739773001, Camera)
[W] 2024-05-18 10:58:07.836 [RealCall.kt:550]: 
java.io.IOException: canceled due to java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 4475360 free bytes and 4370KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:550)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 4475360 free bytes and 4370KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
		at okio.Segment.<init>(Segment.kt:62)
		at okio.SegmentPool.take(SegmentPool.kt:90)
		at okio.Buffer.writableSegment$okio(Buffer.kt:1499)
		at okio.Buffer.write(Buffer.kt:1290)
		at okio.RealBufferedSink.write(RealBufferedSink.kt:184)
		at okhttp3.internal._RequestBodyCommonKt$commonToRequestBody$1.writeTo(-RequestBodyCommon.kt:36)
		at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.kt:159)
		at okhttp3.MultipartBody.writeTo(MultipartBody.kt:99)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:64)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at com.savvasdalkitsis.uhuruphotos.feature.auth.domain.implementation.service.TokenRefreshInterceptor.intercept(TokenRefreshInterceptor.kt:31)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:233)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)

[...]

[V] 2024-05-18 10:58:07.931 [Log.kt:27]: Found item (-1313584517, Screenshots)
[E] 2024-05-18 10:58:09.857 [Segment.kt:62]: 
java.lang.OutOfMemoryError: Failed to allocate a 8208 byte allocation with 4475360 free bytes and 4370KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at okio.Segment.<init>(Segment.kt:62)
	
[...]
```
